/**
 * Copyright (c) 2022, Jason He. All rights reserved.
 */

package com.github.hetianyi.plugin.template.model.form;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import com.github.hetianyi.boot.ready.common.Convertible;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 创建示例请求表单
 * 
 * <br><br>
 * This class is automatically generated by
 * <a href="https://github.com/hetianyi/code-generator-plugin">code-generator-plugin</a>.
 * 
 * @author Jason He
 */
@ApiModel(description = "创建示例请求表单")
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class CreateExampleForm implements Convertible<CreateExampleForm> {

    /** 用户名 */
    @ApiModelProperty("用户名")
    @NotEmpty(message = "用户名不能为空")
    @Pattern(regexp =  "[a-z][0-9a-z_]{5,20}", message = "用户名格式错误")
    private String username;

    /** 昵称 */
    @ApiModelProperty("昵称")
    @Size(max = 10, message = "昵称最长为10个字符")
    private String nickname;
}